version: "3"
services:
  my5grantester:
    build:
      context: ./
    container_name: my5grantester
    privileged: true
    command: ./app ${TEST_PARAMETERS}
    volumes:
      - ./config/tester.yaml:/workspace/my5G-RANTester/config/config.yml
    cap_add:
      - NET_ADMIN
    networks:
      default:
        aliases:
          - tester.free5gc.org

  iperf:
    image: mlabbe/iperf:latest
    container_name: iperf
    ports:
      - 5001:5001
    command: -s
    networks:
      dn-net:
        ipv4_address: 10.60.0.100

networks:
  default:
    external:
      name: "free5gc-compose_default"
  free5gc-compose_dn-net:
    external: true
